### ISSUE TITLE
ACTRIS-Norway; use-case 3 FLEXPART and eBC

### ISSUE THREAD

**Issue by lisemurberg** [ACTRIS-Data-Centre/actris-jupyter-hub#13]
Make a product where you can plot FLEXPART modelled BC either visualized together with the source spectrum or continental spectrum over 1 month with observational eBC from the corresponding stations. eBC lev3 products will be available in the portal for filter absorption photometer QA data.  
_Main aim: Improve the knowledge of black carbon in Europe, both spatial distribution at ground and with height and the sources and variations on various time scale e.g. 3 hourly, daily and monthly scale._

**Comment by maritsandstad** [comment]
@tovesv, maybe link this issue to your PR? That way it's easier to see what belongs together (Under Development on the right here you can pull down, I think maybe your PR is  #21 ?)

**Comment by tovesv** [comment]
@maritsandstad, I need to get more familiar with github....

**Comment by maritsandstad** [comment]
@tovesv, hopefully this can be a fun and rewarding opportunity to do so ;-)
