### ISSUE TITLE
json decode not working?

### ISSUE THREAD

**Issue by MichaelSchulzMETNO** [ACTRIS-Data-Centre/actris-jupyter-hub#6]
When I try to use example 2) on the nird jupyterhub, for the escience course, it runs until

# get all metadata from station Birkenes II (9cxe) in catalogue ### 
response = requests.get("https://dev-actris-md.nilu.no/Metadata/facility/9cxe") 
metadata_archive = response.json() 
metadata_archive # show metadata

JSONDecodeError                           Traceback (most recent call last)
File [/opt/conda/lib/python3.11/site-packages/requests/models.py:971](https://image-test.craas1.sigma2.no/opt/conda/lib/python3.11/site-packages/requests/models.py#line=970), in Response.json(self, **kwargs)
    970 try:
--> 971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File [/opt/conda/lib/python3.11/json/__init__.py:346](https://image-test.craas1.sigma2.no/opt/conda/lib/python3.11/json/__init__.py#line=345), in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:

File [/opt/conda/lib/python3.11/json/decoder.py:337](https://image-test.craas1.sigma2.no/opt/conda/lib/python3.11/json/decoder.py#line=336), in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File [/opt/conda/lib/python3.11/json/decoder.py:355](https://image-test.craas1.sigma2.no/opt/conda/lib/python3.11/json/decoder.py#line=354), in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
Cell In[11], line 3
      1 # get all metadata from station Birkenes II (9cxe) in catalogue 
      2 response = requests.get("https://dev-actris-md.nilu.no/Metadata/facility/9cxe") 
----> 3 metadata_archive = response.json() 
      4 metadata_archive # show metadata

File /opt/conda/lib/python3.11/site-packages/requests/models.py:975, in Response.json(self, **kwargs)
    971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by MichaelSchulzMETNO** [comment]
maybe related::

example 3: 
abs_list[0]['md_distribution_information']

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[7], line 2
      1 # Each file have
----> 2 abs_list[0]['md_distribution_information']

IndexError: list index out of range

**Comment by lisemurberg** [comment]
Due to errors in API. Updates to API are in progress.
