### ISSUE TITLE
NRT example 7 not finding thredds catalogue?

### ISSUE THREAD

**Issue by MichaelSchulzMETNO** [ACTRIS-Data-Centre/actris-jupyter-hub#8]
Cell 2 of example 7

all_opendap_urls = threddsclient.opendap_urls('https://thredds.nilu.no/thredds/catalog/actris_nrt/catalog.xml')
dmps_opendap_urls = [x for x in all_opendap_urls if 'dmps' in x]
print('All NRT dmps datasets with opendap protocol: \n',dmps_opendap_urls)
smps_opendap_urls = [x for x in all_opendap_urls if 'smps' in x]
print('\nAll NRT smps datasets with opendap protocol: \n',smps_opendap_urls)

produces this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File [/opt/conda/envs/pangeo-notebook/lib/python3.11/site-packages/threddsclient/client.py:71](https://escience2024.craas1.sigma2.no/opt/conda/envs/pangeo-notebook/lib/python3.11/site-packages/threddsclient/client.py#line=70), in read_xml(xml, baseurl, skip)
     70     soup = BSoup(xml, 'xml').catalog
---> 71     soup.name  # Xml should contain <catalog[/](https://escience2024.craas1.sigma2.no/)> at top level
     72 except AttributeError:

AttributeError: 'NoneType' object has no attribute 'name'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[3], line 2
      1 # Get the ACTRIS NRT thredds catalog
----> 2 all_opendap_urls = threddsclient.opendap_urls('https://thredds.nilu.no/thredds/catalog/actris_nrt/catalog.xml')
      4 # Get all DMPS opendap urls
      5 dmps_opendap_urls = [x for x in all_opendap_urls if 'dmps' in x]

File /opt/conda/envs/pangeo-notebook/lib/python3.11/site-packages/threddsclient/client.py:15, in opendap_urls(url, skip, **kwargs)
     11 def opendap_urls(url, skip=None, **kwargs):
     12     """
     13     Returns a list of OpenDAP urls listed in the catalog at `url`
     14     """
---> 15     return read_url(url, skip, **kwargs).opendap_urls()

File [/opt/conda/envs/pangeo-notebook/lib/python3.11/site-packages/threddsclient/client.py:52](https://escience2024.craas1.sigma2.no/opt/conda/envs/pangeo-notebook/lib/python3.11/site-packages/threddsclient/client.py#line=51), in read_url(url, skip, **kwargs)
     50 url = fix_catalog_url(url)
     51 req = requests.get(url, **kwargs)
---> 52 return read_xml(req.text, url)

File [/opt/conda/envs/pangeo-notebook/lib/python3.11/site-packages/threddsclient/client.py:73](https://escience2024.craas1.sigma2.no/opt/conda/envs/pangeo-notebook/lib/python3.11/site-packages/threddsclient/client.py#line=72), in read_xml(xml, baseurl, skip)
     71     soup.name  # Xml should contain <catalog[/](https://escience2024.craas1.sigma2.no/)> at top level
     72 except AttributeError:
---> 73     raise ValueError("Does not appear to be a Thredds catalog")
     75 return Catalog(soup, baseurl, skip)

ValueError: Does not appear to be a Thredds catalog**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lisemurberg** [comment]
Problem with thredds catalog fixed.
